
set -g default-terminal 'xterm-256color' # Set xterm_color

set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

unbind r
bind r source-file ~/.tmux.conf

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind -r m resize-pane -Z

# some QoL
set-option -g allow-rename off
set-option -g renumber-windows on

# color scheme
set -ogq @BG_COLOR "#fab387"
set -ogq @FG_COLOR "#212121"
set -ogq @LAVENDER "#b4befe"
set -ogq @TEAL "#94e2d5"
set -ogq @SKY "#313244"
set -ogq @SAPPHIRE "#45475a"
set -ogq @CRUST "#11111b"

# statusbar
set -g status-position top
set -g status-justify absolute-centre
set-option -g status-style bg=default

# sides
set -g status-left ' #S '
set -g status-left-style 'fg=#{@FG_COLOR},bold,bg=#{@BG_COLOR}'

set -g status-right-style 'fg=#{@BG_COLOR},bold,bg=#{@CRUST}'
set -g status-right ' %a, %d %h %-I:%M %p '
set -g status-right-length 50

# window
setw -g window-status-current-style 'fg=#{@FG_COLOR},bold,bg=#{@BG_COLOR}'
setw -g window-status-current-format ' #I #W '

setw -g window-status-style 'fg=#{@BG_COLOR} bg=#{@FG_COLOR}'
setw -g window-status-format ' #I #W '

set -g mouse on


# i List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin  'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

run '~/.tmux/plugins/tpm/tpm'


